apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gifs-website
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=true
  project: default
  source:
    repoURL: https://github.com/noaavisrur/flask-project.git
    path: helm
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gifs-website
