apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-compose-container
          image: {{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PORT
              value: "3306"
          # Add additional configurations for the Flask container

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql-compose-container
  template:
    metadata:
      labels:
        app: mysql-compose-container
    spec:
      containers:
        - name: mysql-compose-container
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          # Add additional configurations for the MySQL container

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql-compose-container
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
